services:
  docs:
    image: bottom_up_local_docs
    container_name: bottom_up_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./bottom_up:/app/bottom_up:z
    ports:
      - '9000:9000'
    command: /start-docs
